#!/bin/bash
ln -s ~/.dotfiles/.bashrc ~/.bashrc
ln -s ~/.dotfiles/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/.profile ~/.profile
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.stellarium/config.ini ~/.stellarium/config.ini
ln -s ~/.dotfiles/.vscode/settings.json ~/.config/Code/User/settings.json
ln -s ~/.dotfiles/.vscode/keybindings.json ~/.config/Code/User/keybindings.json
ln -s ~/.dotfiles/.vscode/snippets ~/.config/Code/User/snippets
ln -s ~/.dotfiles/.vscode/extensions.json ~/.config/Code/User/extensions.json

echo 'Symlinks created'

sudo apt-get -y update
sudo apt-get -y upgrade

echo 'Installing all packages expressly installed by apt (packages-apt.txt)... This may take a while...'
sudo apt-get -y install $(cat ../packages/packages-apt-development.txt)

echo 'installing all packages expressly installed by pip (packages-pip.txt)... This may take a while...'
sudo pip install $(cat ../packages/packages-pip.txt)

echo 'installing nvm...'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash